import {
    users_db,
    sent_messages_db,
    contacts_db,
    received_messages_db,
} from "../database/db.js"; // importing temporary db

export const resolvers = {
    Query: {
        // Query to get all users in the DB cluster
        // Usecases: Searching of User
        getAllUsers: () => users_db,

        // Query to get an particular user 
        getUser: (parent, args) => users_db.find((user) => user.id === args.id),

        // Query to get all the contacts of queried user
        getUserContacts: (parent, args) =>
            users_db.find((user) => user.id == args.id).contacts,
    },
    Mutation: {
        // Used to create the user with unique token generated by Firebase, email, username
        createUser: (parent, args) => {
            const { email, username } = args;
            const rid = String(Math.random()) // replaces by firebase token
            const user = {
                id: rid,
                email,
                username,
                contacts: [],
                sentMessages: [],
                receivedMessages: [],
            };
            users_db.push(user);
            return user;
        },
        // Add contact to the concerned user,
        // In this we search the user using 'firebase token' then
        // insert the created contact into it
        addContactToUser: (parent, args) => {
            const { userid, email, username } = args;
            const rid = String(Math.random());
            const newContact = {
                id: rid,
                email,
                username,
            };
            contacts_db.push(newContact);
            const user = users_db.find((user) => user.id === userid);
            user.contacts.push(newContact);
            return newContact;
        },
        // TODO: Implement SentMessage & Received Message Handlers
    },
};